openapi: 3.0.0
info:
  title: Retroko API Access
  version: 1.0.0
paths:
  internal-status:
    get:
      summary: Vérifier l'etat interne de Retroko
      security:
        - ApiKeyAuth: []
      responses: 
        '200':
          description: OK
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
